// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.8.0
// source: category_message.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Category_Category int32

const (
	Category_Fruit     Category_Category = 0
	Category_Flower    Category_Category = 1
	Category_Tree      Category_Category = 2
	Category_Vegetable Category_Category = 3
	Category_Fancy     Category_Category = 4
)

// Enum value maps for Category_Category.
var (
	Category_Category_name = map[int32]string{
		0: "Fruit",
		1: "Flower",
		2: "Tree",
		3: "Vegetable",
		4: "Fancy",
	}
	Category_Category_value = map[string]int32{
		"Fruit":     0,
		"Flower":    1,
		"Tree":      2,
		"Vegetable": 3,
		"Fancy":     4,
	}
)

func (x Category_Category) Enum() *Category_Category {
	p := new(Category_Category)
	*p = x
	return p
}

func (x Category_Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Category_Category) Descriptor() protoreflect.EnumDescriptor {
	return file_category_message_proto_enumTypes[0].Descriptor()
}

func (Category_Category) Type() protoreflect.EnumType {
	return &file_category_message_proto_enumTypes[0]
}

func (x Category_Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Category_Category.Descriptor instead.
func (Category_Category) EnumDescriptor() ([]byte, []int) {
	return file_category_message_proto_rawDescGZIP(), []int{0, 0}
}

type Category struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category Category_Category `protobuf:"varint,1,opt,name=category,proto3,enum=golang_grpc_unary_stream.plant.Category_Category" json:"category,omitempty"`
}

func (x *Category) Reset() {
	*x = Category{}
	if protoimpl.UnsafeEnabled {
		mi := &file_category_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_category_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_category_message_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetCategory() Category_Category {
	if x != nil {
		return x.Category
	}
	return Category_Fruit
}

var File_category_message_proto protoreflect.FileDescriptor

var file_category_message_proto_rawDesc = []byte{
	0x0a, 0x16, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67,
	0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x75, 0x6e, 0x61, 0x72, 0x79, 0x5f, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x22, 0xa0, 0x01, 0x0a, 0x08, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x4d, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x31, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67,
	0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x75, 0x6e, 0x61, 0x72, 0x79, 0x5f, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x22, 0x45, 0x0a, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x12, 0x09, 0x0a, 0x05, 0x46, 0x72, 0x75, 0x69, 0x74, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46,
	0x6c, 0x6f, 0x77, 0x65, 0x72, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x72, 0x65, 0x65, 0x10,
	0x02, 0x12, 0x0d, 0x0a, 0x09, 0x56, 0x65, 0x67, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x10, 0x03,
	0x12, 0x09, 0x0a, 0x05, 0x46, 0x61, 0x6e, 0x63, 0x79, 0x10, 0x04, 0x42, 0x04, 0x5a, 0x02, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_category_message_proto_rawDescOnce sync.Once
	file_category_message_proto_rawDescData = file_category_message_proto_rawDesc
)

func file_category_message_proto_rawDescGZIP() []byte {
	file_category_message_proto_rawDescOnce.Do(func() {
		file_category_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_category_message_proto_rawDescData)
	})
	return file_category_message_proto_rawDescData
}

var file_category_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_category_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_category_message_proto_goTypes = []interface{}{
	(Category_Category)(0), // 0: golang_grpc_unary_stream.plant.Category.Category
	(*Category)(nil),       // 1: golang_grpc_unary_stream.plant.Category
}
var file_category_message_proto_depIdxs = []int32{
	0, // 0: golang_grpc_unary_stream.plant.Category.category:type_name -> golang_grpc_unary_stream.plant.Category.Category
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_category_message_proto_init() }
func file_category_message_proto_init() {
	if File_category_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_category_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_category_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_category_message_proto_goTypes,
		DependencyIndexes: file_category_message_proto_depIdxs,
		EnumInfos:         file_category_message_proto_enumTypes,
		MessageInfos:      file_category_message_proto_msgTypes,
	}.Build()
	File_category_message_proto = out.File
	file_category_message_proto_rawDesc = nil
	file_category_message_proto_goTypes = nil
	file_category_message_proto_depIdxs = nil
}
