// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.8.0
// source: plant_message.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Plant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category    *Category `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Price       float32   `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Avatar      string    `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Description string    `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Plant) Reset() {
	*x = Plant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plant_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Plant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plant) ProtoMessage() {}

func (x *Plant) ProtoReflect() protoreflect.Message {
	mi := &file_plant_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plant.ProtoReflect.Descriptor instead.
func (*Plant) Descriptor() ([]byte, []int) {
	return file_plant_message_proto_rawDescGZIP(), []int{0}
}

func (x *Plant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Plant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Plant) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *Plant) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Plant) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Plant) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_plant_message_proto protoreflect.FileDescriptor

var file_plant_message_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x5f, 0x67, 0x72,
	0x70, 0x63, 0x5f, 0x75, 0x6e, 0x61, 0x72, 0x79, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e,
	0x70, 0x6c, 0x61, 0x6e, 0x74, 0x1a, 0x16, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc1, 0x01,
	0x0a, 0x05, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x44, 0x0a, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e,
	0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x75, 0x6e, 0x61, 0x72,
	0x79, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x2e, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x42, 0x04, 0x5a, 0x02, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plant_message_proto_rawDescOnce sync.Once
	file_plant_message_proto_rawDescData = file_plant_message_proto_rawDesc
)

func file_plant_message_proto_rawDescGZIP() []byte {
	file_plant_message_proto_rawDescOnce.Do(func() {
		file_plant_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_plant_message_proto_rawDescData)
	})
	return file_plant_message_proto_rawDescData
}

var file_plant_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_plant_message_proto_goTypes = []interface{}{
	(*Plant)(nil),    // 0: golang_grpc_unary_stream.plant.Plant
	(*Category)(nil), // 1: golang_grpc_unary_stream.plant.Category
}
var file_plant_message_proto_depIdxs = []int32{
	1, // 0: golang_grpc_unary_stream.plant.Plant.category:type_name -> golang_grpc_unary_stream.plant.Category
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_plant_message_proto_init() }
func file_plant_message_proto_init() {
	if File_plant_message_proto != nil {
		return
	}
	file_category_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_plant_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Plant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plant_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plant_message_proto_goTypes,
		DependencyIndexes: file_plant_message_proto_depIdxs,
		MessageInfos:      file_plant_message_proto_msgTypes,
	}.Build()
	File_plant_message_proto = out.File
	file_plant_message_proto_rawDesc = nil
	file_plant_message_proto_goTypes = nil
	file_plant_message_proto_depIdxs = nil
}
